### ISSUE TITLE
readme doesnt render on pypi

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [python-manage/manage#15] opened 2017-06-05 07:29 UTC

**Comment by RodolfoFerro** [comment] 2017-10-04 17:32
As mentioned in https://stackoverflow.com/questions/17401132/restructuredtext-readme-rst-not-parsing-on-pypi, you might be using a different version of support docutils.

**Comment by RonnyPfannschmidt** [comment] 2017-10-05 06:10
my version of docutils is not relevant to pypi at all ^^

**Comment by jorgeecardona** [comment] 2021-02-06 16:25
Duplicate of #10

**Closed by jorgeecardona** 2021-02-06 16:25 UTC
Labels: hacktoberfest
